/* Generated by Cython 3.0.12 */

#ifndef __PYX_HAVE__algo_engine__base__market_data
#define __PYX_HAVE__algo_engine__base__market_data

#include "Python.h"

/* "algo_engine/base/market_data.pxd":42
 *         SIDE_SHORT
 * 
 * cdef public enum OrderType:             # <<<<<<<<<<<<<<
 *     ORDER_UNKNOWN = 2
 *     ORDER_CANCEL = 1
 */
enum OrderType {
  ORDER_UNKNOWN = 2,
  ORDER_CANCEL = 1,
  ORDER_GENERIC = 0,
  ORDER_LIMIT = 10,
  ORDER_LIMIT_MAKER = 11,
  ORDER_MARKET = 20,
  ORDER_FOK = 21,
  ORDER_FAK = 22,
  ORDER_IOC = 23
};

/* "algo_engine/base/market_data.pxd":54
 * 
 * 
 * cdef public enum OrderState:             # <<<<<<<<<<<<<<
 *     STATE_UNKNOWN = 0
 *     STATE_REJECTED = 1  # order rejected
 */
enum OrderState {
  STATE_UNKNOWN = 0,
  STATE_REJECTED = 1,
  STATE_INVALID = 2,
  STATE_PENDING = 3,
  STATE_SENT = 4,
  STATE_PLACED = 5,
  STATE_PARTFILLED = 6,
  STATE_FILLED = 7,
  STATE_CANCELING = 8,
  STATE_CANCELED = 9
};

#ifndef __PYX_HAVE_API__algo_engine__base__market_data

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

#endif /* !__PYX_HAVE_API__algo_engine__base__market_data */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initmarket_data(void);
#else
/* WARNING: Use PyImport_AppendInittab("market_data", PyInit_market_data) instead of calling PyInit_market_data directly from Python 3.5 */
PyMODINIT_FUNC PyInit_market_data(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"market_data\", PyInit_market_data) instead of calling PyInit_market_data directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"market_data\", PyInit_market_data) instead of calling PyInit_market_data directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"market_data\", PyInit_market_data) instead of calling PyInit_market_data directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_market_data_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_market_data() __PYX_WARN_IF_PyInit_market_data_INIT_CALLED(PyInit_market_data())
#endif
#endif

#endif /* !__PYX_HAVE__algo_engine__base__market_data */
